### ISSUE TITLE
Add hardware reminder to TTL sync page

### ISSUE THREAD

**Issue by matiasandina** [open-ephys/acq-board-docs#6]
Thank you for adding the bonsai sketch in [this link](https://open-ephys.github.io/acq-board-docs/Tutorials/bonsai-acquisition.html).
Wanted to point out that it might be nice to have a reminder of this pic (spent a few minutes with the HDMI connected to the Analog in :smiling_face_with_tear: ). A link to the pic would suffice.

![image](https://user-images.githubusercontent.com/7494967/188182480-866e0b13-f9e1-43af-82c7-1295ee4608fc.png)

**Comment by jsiegle** [comment]
Hi Matias – thanks for this suggestion! Because the identity of these connectors is so important, I added reminders in 3 places:

1. On the [Peripheral devices](https://open-ephys.github.io/acq-board-docs/User-Manual/Peripheral-devices.html) page.
2. In the [Synchronizing with a behavioral camera](https://open-ephys.github.io/acq-board-docs/Tutorials/Ephys-with-behavioural-camera.html) tutorial
3. In the ["Customize the workflow"](https://open-ephys.github.io/acq-board-docs/Tutorials/bonsai-acquisition.html#customize-the-workflow) section of the Bonsai tutorial.
